backend:
  name: github
  repo: uptheirons78/studio-barberio

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: "sentenza"
    label: "Sentenze"
    folder: "content/sentenze"
    create: true
    identifier_field: "titolo"
    fields:
      - { name: "path", label: "Path" }
      - { name: "data", label: "Data Articolo", widget: "date" }
      - { name: "titolo", label: "Titolo" }
      - { name: "descrizione", label: "Descrizione" }
      - { name: "sentenza", label: "PDF Sentenza", widget: "file", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "articolo"
    label: "Articoli"
    folder: "content/articoli"
    create: true
    identifier_field: "titolo"
    fields:
      - { name: "path", label: "Path" }
      - { name: "data", label: "Data Articolo", widget: "date" }
      - { name: "titolo", label: "Titolo" }
      - { name: "descrizione", label: "Descrizione" }
      - { name: "link", label: "Indirizzo Articolo", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - { name: "body", label: "Body", widget: "markdown" }
      - file: "src/pages/chi-siamo.md"
        label: "Chi Siamo"
        name: "chi-siamo"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Titolo", name: "title", widget: "string"}
          - {label: "Descrizione Attività dello Studio Barberio", name: "body", widget: "markdown"}
          - {label: "Membri del Team", name: "members", widget: "list", fields: [{label: "Nome", name: "nome", widget: "string"}, {label: "Occupazione", name: "occupazione", widget: "string"}, {label: "Breve Descrizione", name: "breve-descrizione", widget: "string"}, {label: "Email", name: "email", widget: "string"}, {label: "Telefono", name: "telefono", widget: "string"}, {label: "Facebook", name: "facebook", widget: "string"}, {label: "Twitter", name: "twitter", widget: "string"}, {label: "Linkedin", name: "linkedin", widget: "string"}, {label: "Descrizione", name: "descrizione", widget: "markdown"}]}
