backend:
  name: github
  repo: uptheirons78/studio-barberio

media_folder: static/assets
public_folder: assets

collections:
  - name: "articolo"
    label: "Articolo"
    folder: "content/articoli"
    create: true
    identifier_field: "titolo"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "articoli"}
      - { name: "titolo", label: "Titolo" }
      - { name: "data", label: "Data Articolo", widget: "date" }
      - { name: "descrizione", label: "Descrizione" }
      - { name: "link", label: "Link Articolo", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "sentenza"
    label: "Sentenze"
    folder: "content/sentenze"
    create: true
    identifier_field: "titolo"
    fields:
      - { name: "path", label: "Path" }
      - { name: "data", label: "Data Articolo", widget: "date" }
      - { name: "titolo", label: "Titolo" }
      - { name: "descrizione", label: "Descrizione" }
      - { name: "sentenza", label: "PDF Sentenza", widget: "file", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
