backend:
  name: github
  repo: uptheirons78/studio-barberio

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
  - name: "sentenza"
    label: "Sentenze"
    folder: "content/sentenze"
    create: true
    identifier_field: "titolo"
    fields:
      - { name: "path", label: "Path" }
      - { name: "data", label: "Data Articolo", widget: "date" }
      - { name: "titolo", label: "Titolo" }
      - { name: "descrizione", label: "Descrizione" }
      - { name: "sentenza", label: "PDF Sentenza", widget: "file", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "articolo"
    label: "Articoli"
    folder: "content/articoli"
    create: true
    identifier_field: "titolo"
    fields:
      - { name: "path", label: "Path" }
      - { name: "data", label: "Data Articolo", widget: "date" }
      - { name: "titolo", label: "Titolo" }
      - { name: "descrizione", label: "Descrizione" }
      - { name: "link", label: "Indirizzo Articolo", widget: "string", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - { name: "body", label: "Body", widget: "markdown" }
